#!/usr/bin/env python3
"""Convert an Azoteq IQS5xx-B000 GUI ("BL" format) Intel-HEX export into a C image
for the in-firmware I2C bootloader flasher (iqs5xx_bootloader.c).

Usage: python hex2c.py <file.hex> <out.h>

The image covers the whole programmable map 0x83C0..0xBFFF (15424 bytes), 0x00-filled
where the hex has no record (same as the Linux iqs5xx driver). Settings registers 0x0400..0x06FF of
the I2C memory map live at flash offset 0xB92B + reg; the export version (reg 0x0677)
is extracted so the runtime can decide whether the module already carries this image.
"""
import sys, os, datetime

CHKSM, PMAP_END = 0x83C0, 0xBFFF
PMAP_LEN = PMAP_END + 1 - CHKSM
SETTINGS_BASE = 0xB92B

def parse(path):
    mem = {}
    for line in open(path):
        line = line.strip()
        if not line.startswith(':'):
            continue
        b = bytes.fromhex(line[1:])
        n, addr, typ = b[0], (b[1] << 8) | b[2], b[3]
        if typ == 1:
            break
        if typ != 0:
            raise SystemExit(f"unsupported record type {typ}")
        if sum(b) & 0xFF:
            raise SystemExit(f"bad checksum: {line}")
        for i, x in enumerate(b[4:4 + n]):
            a = addr + i
            if not (CHKSM <= a <= PMAP_END):
                raise SystemExit(f"address 0x{a:04X} outside programmable map")
            mem[a] = x
    return mem

def main():
    src, out = sys.argv[1], sys.argv[2]
    mem = parse(src)
    img = bytes(mem.get(a, 0x00) for a in range(CHKSM, PMAP_END + 1))  # 0x00 fill matches the Linux iqs5xx driver (kzalloc), field-proven with vendor exports
    def reg(r): return img[SETTINGS_BASE + r - CHKSM]
    export_ver = (reg(0x0677) << 8) | reg(0x0678)
    with open(out, 'w') as f:
        f.write(f"/* Generated by hex2c.py from {os.path.basename(src)} on {datetime.date.today()} -- do not edit. */\n")
        f.write("#pragma once\n#include <stdint.h>\n#include \"progmem.h\"\n\n")
        f.write(f"#define IQS5XX_FW_IMAGE_SOURCE \"{os.path.basename(src)}\"\n")
        f.write(f"#define IQS5XX_FW_EXPORT_VERSION {export_ver}\n")
        f.write(f"#define IQS5XX_FW_TOUCH_MULT_SET {reg(0x0596)}\n#define IQS5XX_FW_TOUCH_MULT_CLEAR {reg(0x0597)}\n")
        f.write(f"#define IQS5XX_FW_ATI_TARGET {(reg(0x056D) << 8) | reg(0x056E)}\n\n")
        f.write(f"static const uint8_t iqs5xx_fw_image[{PMAP_LEN}] PROGMEM = {{\n")
        for i in range(0, PMAP_LEN, 16):
            f.write("    " + ", ".join(f"0x{x:02X}" for x in img[i:i + 16]) + ",\n")
        f.write("};\n")
    print(f"{out}: {PMAP_LEN} bytes, export version {export_ver}, touch mult {reg(0x0596)}/{reg(0x0597)}, ATI target {(reg(0x056D) << 8) | reg(0x056E)}")

if __name__ == '__main__':
    main()
